sudo: false
language: ruby
rvm:
  - 2.2.5
before_script:
  - mkdir travis-drivers
  - export PATH=$PWD/travis-drivers:$PATH
  - sh -e /etc/init.d/xvfb start
script:
  - |
    # https://omahaproxy.appspot.com
    # https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/
    # CHROME_REVISION=`curl -s http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/LAST_CHANGE`
      CHROME_REVISION=`curl -s https://omahaproxy.appspot.com/all?csv=1 | awk -F"," '/linux,stable/ {print $8}'`

      curl -L -O "http://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/${CHROME_REVISION}/chrome-linux.zip"
      unzip chrome-linux.zip

      CHROMEDRIVER_VERSION=$(curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
      curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
      unzip chromedriver_linux64.zip

      mv chromedriver travis-drivers/chromedriver
      chmod +x travis-drivers/chromedriver

      bundle exec rake
